backend_project_product_backlog:
    path:     /
    defaults: { _controller: "BackendBundle:Item:productBacklog" }
    methods:  [GET, POST]

backend_project_product_backlog_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Item:new" }
    methods:  [GET, POST]
    
backend_project_product_backlog_edit:
    path:     /{itemId}/edit
    defaults: { _controller: "BackendBundle:Item:edit" }
    methods:  [GET, POST]
    
backend_project_product_backlog_delete:
    path:     /delete
    defaults: { _controller: "BackendBundle:Item:delete" }
    methods:  [POST]
    
backend_project_product_backlog_upload_attachment:
    path:     /{itemId}/uploadAttachment
    defaults: { _controller: "BackendBundle:Item:uploadAttachment" }
    methods:  [POST]
    
backend_project_product_backlog_delete_attachment:
    path:     /deleteAttachment
    defaults: { _controller: "BackendBundle:Item:deleteAttachment" }
    methods:  [POST]
    
backend_project_product_backlog_new_related_item:
    path:     /{itemId}/newRelatedItem
    defaults: { _controller: "BackendBundle:Item:newRelatedItem" }
    methods:  [GET, POST]
    
backend_project_product_backlog_change_priority:
    path:     /changePriority
    defaults: { _controller: "BackendBundle:Item:changePriority" }
    methods:  [POST]
    
backend_project_product_backlog_html_edit_estimation:
    path:     /getHtmlEditEstimation
    defaults: { _controller: "BackendBundle:Item:getHtmlEditEstimation" }
    methods:  [POST]

backend_project_product_backlog_edit_estimation:
    path:     /editEstimation
    defaults: { _controller: "BackendBundle:Item:editEstimation" }
    methods:  [POST]

backend_project_product_backlog_html_edit_worked_time:
    path:     /getHtmlEditWorkedTime
    defaults: { _controller: "BackendBundle:Item:getHtmlEditWorkedTime" }
    methods:  [POST]

backend_project_product_backlog_edit_worked_time:
    path:     /editWorkedTime
    defaults: { _controller: "BackendBundle:Item:editWorkedTime" }
    methods:  [POST]
    
backend_project_product_backlog_html_change_status:
    path:     /getHtmlChangeStatus
    defaults: { _controller: "BackendBundle:Item:getHtmlChangeStatus" }
    methods:  [POST]

backend_project_product_backlog_change_status:
    path:     /changeStatus
    defaults: { _controller: "BackendBundle:Item:changeStatus" }
    methods:  [POST]

backend_project_product_backlog_change_parent:
    path:     /changeParent
    defaults: { _controller: "BackendBundle:Item:changeParent" }
    methods:  [POST]