backend_projects:
    path:     /
    defaults: { _controller: "BackendBundle:Project:index" }
    methods:  GET
    
backend_projects_view:
    path:     /{id}/view
    defaults: { _controller: "BackendBundle:Project:view" }
    methods:  GET

backend_projects_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Project:new" }
    methods:  [GET, POST]

backend_projects_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Project:edit" }
    methods:  [GET, POST]

backend_projects_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Project:delete" }
    methods:  DELETE
    
backend_projects_roles:
        resource: "@BackendBundle/Resources/config/routing/proyectRoles.yml"
        prefix:   /{projectId}/roles    

backend_project_team:
        resource: "@BackendBundle/Resources/config/routing/projectTeam.yml"
        prefix:   /{id}/projectTeam
        
backend_project_product_backlog:
        resource: "@BackendBundle/Resources/config/routing/productBacklog.yml"
        prefix:   /{id}/productBacklog

backend_project_sprints:
        resource: "@BackendBundle/Resources/config/routing/sprint.yml"
        prefix:   /{id}/sprints
